apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidepod
  name: sidepod
spec:
  containers:
    - name: myapp
      image: nginx:latest
      volumeMounts:
        - name: data
          mountPath: /opt
  initContainers:
    - name: logshipper
      image: alpine:latest
      restartPolicy: Always
      command: ['sh', '-c', 'sleep 15']
      volumeMounts:
        - name: data
          mountPath: /opt
  volumes:
    - name: data
      emptyDir: {}