apiVersion: v1
kind: Pod
metadata:
  name: sidepod
spec:
      containers:
        - name: myapp
          image: nginx:latest
      initContainers:
        - name: sidecar
          image: busybox:latest
          restartPolicy: Always
          command: ['sh', '-c', 'sleep 15']